apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventario-app
      version: green
  template:
    metadata:
      labels:
        app: inventario-app
        version: green
    spec:
      containers:
      - name: inventario-app
        image: ghcr.io/ericksalinas30/inventario-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: inventario-secrets
              key: API_KEY
        - name: STARTUP_DELAY_SECONDS
          value: "15"
        - name: APP_VERSION
          value: "v2.0.0-green"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 6